spring.application.name=tickets


# 1. Configuración del DataSource (El puente a AWS)
# Usamos el endpoint que ya verificaste con éxito
spring.datasource.url=jdbc:postgresql://tickets-db.c85aci44gto2.us-east-1.rds.amazonaws.com
spring.datasource.username=salvia_admin
spring.datasource.password=salviadb123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate
# 'update' hará que las tablas se creen solas en AWS cuando corras el programa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Configuración del Puerto
server.port=8081

# ==========================================
# 4. Configuración de Apache Kafka (Productor)
# ==========================================
# ==========================================
# 4. Configuración de Apache Kafka (Productor EC2)
# ==========================================
# Apuntamos a la IP pública de la EC2 en AWS por el puerto 9092
spring.kafka.bootstrap-servers=32.192.137.248:9092

# Serializadores
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

# Esto asegura que el microservicio que consuma el mensaje sepa de qué tipo de clase viene
spring.kafka.producer.properties.spring.json.add.type.headers=true


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_15vFB45j4