spring.application.name=tickets


# 1. Configuración del DataSource (El puente a AWS)
# Usamos el endpoint que ya verificaste con éxito
spring.datasource.url=jdbc:postgresql://tickets-db.c0veucki6auh.us-east-1.rds.amazonaws.com:5432/salvia_tickets
spring.datasource.username=salvia_admin
spring.datasource.password=Salvia2026*
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate
# 'update' hará que las tablas se creen solas en AWS cuando corras el programa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Configuración del Puerto
server.port=8081

# ==========================================
# 4. Configuración de Apache Kafka (Productor)
# ==========================================
# Aquí irán las URLs de tu Amazon MSK. Por ahora dejamos localhost de "placeholder".
spring.kafka.bootstrap-servers=localhost:9092

# Serializadores: Le enseñan a Kafka cómo convertir tus objetos Java en texto (JSON) para enviarlos por la red
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Esto asegura que el microservicio que consuma el mensaje sepa de qué tipo de clase viene
spring.kafka.producer.properties.spring.json.add.type.headers=true